let allDivs = document.getElementsByTagName("div")
console.log(allDivs)
let styleButton = document.querySelectorAll("button")
console.log(styleButton)
let divButton = document.querySelector("div.buttons")
console.log(divButton)
let allDivsButton = document.querySelectorAll("div.buttons")
console.log(allDivsButton)